bind_port = 8094
bind_host = "0.0.0.0"

token_secret = "secret"

db_connection = "postgresql://root@huly.local:26257/defaultdb?sslmode=disable"
db_scheme = "hulykvs"

payload_size_limit = "2mb"

default_workspace_uuid = "bb793ec1-252e-4419-8998-7f220ababdfa"

