name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Log to registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - run: echo VERSION=$(grep '^version =' hulykvs_server/Cargo.toml | cut -d '"' -f 2) >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: hulykvs_server/Dockerfile
          push: true
          tags: "${{ vars.DOCKER_USER }}/hulykvs:${{ env.VERSION }},${{ vars.DOCKER_USER }}/hulykvs:latest"
          platforms: linux/amd64,linux/arm64 


